services:
  postgres:
    image: postgres:latest
    container_name: urls_db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: urls_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urls-network

  backend:
    env_file: .env
    build: .
    container_name: urls_backend_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - urls-network

volumes:
  postgres_data:

networks:
  urls-network:
    driver: bridge